# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: theradiofm
open_collective: theradiofm
ko_fi: theradiofm
tidelift: theradiofm
community_bridge: theradiofm
liberapay: theradiofm
issuehunt: theradiofm
otechie: theradiofm
custom: https://paypal.me/themusicstream/100
